#define SCENARIO_SCALE 1.1

#define PLAYER_LVL1_SPRITE_PATH "assets/img/char/adulto.png"
#define PLAYER_LVL1_SPRITES_NUMB 17
#define PLAYER_LVL1_SPRITES_TIME 0.16

#define PLAYER_LVL1_SCALE SCENARIO_SCALE / 6.3636
#define PLAYER_LVL1_STEP 200
#define PLAYER_LVL1_JUMP -850

#define PLAYER_LVL1_IDLE_START 0
#define PLAYER_LVL1_IDLE_END 1
#define PLAYER_LVL1_IDLE_TIME 0.3

#define PLAYER_LVL1_WALK_START 2
#define PLAYER_LVL1_WALK_END 5
#define PLAYER_LVL1_WALK_TIME 0.1

#define PLAYER_LVL1_JUMP_START 15
#define PLAYER_LVL1_JUMP_END 16
#define PLAYER_LVL1_JUMP_TIME 0.1

#define PLAYER_LVL1_ATTACK_WIDTH 100
#define PLAYER_LVL1_ATTACK_HEIGHT 20
#define PLAYER_LVL1_ATTACK_TIME 0.05
#define PLAYER_LVL1_ATTACK_DAMAGE 10
#define PLAYER_LVL1_ATTACK_START 6
#define PLAYER_LVL1_ATTACK_END 9

#define PLAYER_LVL1_DAMAGED_START 10
#define PLAYER_LVL1_DAMAGED_END 11
#define PLAYER_LVL1_DAMAGED_TIME 0.07