#define PLAYER_LVL0_SPRITE_PATH "assets/img/char/baby-pulando.png"
#define PLAYER_LVL0_SPRITES_NUMB 8
#define PLAYER_LVL0_SPRITES_TIME 0.16
#define PLAYER_LVL0_SCALE 0.1
#define PLAYER_LVL0_STEP 200
#define PLAYER_LVL0_JUMP -800
#define PLAYER_INIT_POS \
    {                   \
        400, 300        \
    }
#define PLAYER_LVL0_ATTACK_WIDTH 100
#define PLAYER_LVL0_ATTACK_HEIGHT 20
#define PLAYER_LVL0_ATTACK_TIME 0.05
#define PLAYER_LVL0_ATTACK_DAMAGE 10
#define PLAYER_LVL0_IDLE_START 0
#define PLAYER_LVL0_IDLE_END 1
#define PLAYER_LVL0_IDLE_TIME 0.1
#define PLAYER_LVL0_WALK_START 0
#define PLAYER_LVL0_WALK_END 7
#define PLAYER_LVL0_WALK_TIME 0.1
#define PLAYER_LVL0_JUMP_START 0
#define PLAYER_LVL0_JUMP_END 7
#define PLAYER_LVL0_JUMP_TIME 0.08