#define SCENARIO_SCALE 1.0

#define PLAYER_LVL2_SPRITE_PATH "assets/img/char/aquatico.png"
#define PLAYER_LVL2_SPRITES_NUMB 6
#define PLAYER_LVL2_SPRITES_TIME 0.1

#define PLAYER_LVL2_SCALE SCENARIO_SCALE / 10.3636
#define PLAYER_LVL2_STEP 200
#define PLAYER_LVL2_JUMP -850

#define PLAYER_LVL2_IDLE_START 0
#define PLAYER_LVL2_IDLE_END 1
#define PLAYER_LVL2_IDLE_TIME 0.1

#define PLAYER_LVL2_SWIM_START 0
#define PLAYER_LVL2_SWIM_END 5
#define PLAYER_LVL2_SWIM_TIME 0.15

