#define ENTOKRATON_2_SPRITE_PATH "assets/img/char/alien2.png"
#define ENTOKRATON_2_SPRITES_NUMB 6
#define ENTOKRATON_2_SPRITES_TIME 0.1
#define ENTOKRATON_2_SCALE 0.1
#define ENTOKRATON_2_COLLISION_SCALE 0.6
#define ENTOKRATON_2_INIT_POS \
    {                         \
        2900, 500              \
    }

#define ENTOKRATON_2_IDLE_START 3
#define ENTOKRATON_2_IDLE_END 3
#define ENTOKRATON_2_IDLE_TIME 0.1

#define ENTOKRATON_2_SWIM_START 0
#define ENTOKRATON_2_SWIM_END 3
#define ENTOKRATON_2_SWIM_TIME 0.15

#define ENTOKRATON_2_DIE_START 4
#define ENTOKRATON_2_DIE_END 5
#define ENTOKRATON_2_DIE_TIME 0.25

#define ENTOKRATON_2_HP 100
#define ENTOKRATON_2_STEP 150
#define ENTOKRATON_2_COOLDOWN 0.5
#define ENTOKRATON_2_SWIM_RANGE 200
#define ENTOKRATON_2_STOP_RANGE 5

#define WALK_RANGE 200
#define STOP_RANGE 5