#define ENTOKRATON_1_SPRITE_PATH "assets/img/char/alien1_complete_movement.png"
#define ENTOKRATON_1_SPRITES_NUMB 17
#define ENTOKRATON_1_SPRITES_TIME 0.1
#define ENTOKRATON_1_SCALE 0.2
#define ENTOKRATON_1_INIT_POS \
    {                         \
        600, 300              \
    }

#define ENTOKRATON_1_IDLE_START 7
#define ENTOKRATON_1_IDLE_END 8
#define ENTOKRATON_1_IDLE_TIME 0.1

#define ENTOKRATON_1_WALK_START 13
#define ENTOKRATON_1_WALK_END 16
#define ENTOKRATON_1_WALK_TIME 0.1

#define ENTOKRATON_1_ATTACK_START 0
#define ENTOKRATON_1_ATTACK_END 6
#define ENTOKRATON_1_ATTACK_ANIMATION_TIME 0.1

#define ENTOKRATON_1_DIE_START 9
#define ENTOKRATON_1_DIE_END 12
#define ENTOKRATON_1_DIE_TIME 0.12

#define ENTOKRATON_1_HP 100
#define ENTOKRATON_1_IDLE1_SOUND "assets/audio/alien1/alien 1 - idle 1.ogg"
#define ENTOKRATON_1_IDLE2_SOUND "assets/audio/alien1/alien 1 - idle 2.ogg"
#define ENTOKRATON_1_WALK1_SOUND "assets/audio/alien1/alien 1 - andar.ogg"
#define ENTOKRATON_1_ATTACK_SOUND "assets/audio/alien1/alien 1 - ataque 1.ogg"
#define ENTOKRATON_1_STEP 150
#define ENTOKRATON_1_COOLDOWN 2
#define ENTOKRATON_1_PERCEPTION 300
#define ENTOKRATON_1_ATTACK_RANGE 30
#define ENTOKRATON_1_WALK_RANGE 200
#define ENTOKRATON_1_STOP_RANGE 5
#define ENTOKRATON_1_ATTACK_WIDTH 30
#define ENTOKRATON_1_ATTACK_HEIGHT 100
#define ENTOKRATON_1_ATTACK_TIME 0.05
#define ENTOKRATON_1_ATTACK_DAMAGE 5
#define ENEMY_1_IDLE_START 0
#define ENEMY_1_IDLE_END 2
#define ENEMY_1_IDLE_TIME 0.1
#define ENEMY_1_WALK_START 3
#define ENEMY_1_WALK_END 6
#define ENEMY_1_WALK_TIME 0.1
#define ENEMY_1_COOLDOWN 2
#define ENEMY_1_STEP 150
#define ENEMY_1_PERCEPTION 250
#define ENEMY_1_ATTACK_RANGE 30
#define WALK_RANGE 200
#define STOP_RANGE 5